version: "3.8"

services:
  kaiburr:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: kaiburr_server
    volumes:
      # Mount Jedi Academy base installation
      - ../../dockerize:/app/jediacademy
      # Mount kaiburr source code
      - ..:/app/jediacademy/gamedata/kaiburr
      # Mount persistent config storage (overlays specific config files)
      - ../../configstore_kaiburr:/app/jediacademy/gamedata/kaiburr
    ports:
      - "29070:29070/udp"
      - "29070:29070/tcp"
    restart: unless-stopped
    tty: true